version: '2'
services:
  zabbix-mysql:
    image: mysql:5.7
    container_name: zabbix-mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    ports:
      - 3306:3306
    volumes:
      - zabbix-mysql-data:/var/lib/mysql
    networks:
        zabbix-network:

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: root
      MYSQL_PASSWORD: zabbix
      ZBX_JAVAGATEWAY: zabbix-java-gateway
      ZBX_STARTDISCOVERERS: 3
    depends_on:
      - zabbix-mysql
    ports:
      - 10051:10051	
    volumes:
      - zabbix-alertscripts:/usr/lib/zabbix/alertscripts
      - zabbix-externalscripts:/usr/lib/zabbix/externalscripts
      - zabbix-enc:/var/lib/zabbix/enc
      - zabbix-mibs:/var/lib/zabbix/mibs
      - zabbix-modules:/var/lib/zabbix/modules
      - zabbix-snmptraps:/var/lib/zabbix/snmptraps
      - zabbix-ssh_keys:/var/lib/zabbix/ssh_keys
      - zabbix-ssl-certs:/var/lib/zabbix/ssl/certs
      - zabbix-ssl-keys:/var/lib/zabbix/ssl/keys
      - zabbix-ssl-ssl_ca:/var/lib/zabbix/ssl/ssl_ca


    networks:
        zabbix-network:

  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: zabbix-web-nginx
    restart: always
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: root
      MYSQL_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Asia/Shanghai   
    depends_on:
      - zabbix-mysql
      - zabbix-server
    ports:
      - 4000:80
    volumes:
      - zabbix-web-data:/usr/share/zabbix
    networks:
        zabbix-network:

  zabbix-server-agent:
      image: zabbix/zabbix-agent:latest
      container_name: zabbix-server-agent
      environment:
        ZBX_HOSTNAME: "Zabbix server"
        ZBX_SERVER_HOST: 172.19.0.1
        ZBX_SERVER_PORT: 10051
      depends_on:
        - zabbix-server
      ports:
        - 10050:10050
      networks:
        zabbix-network:

volumes: 
  zabbix-alertscripts:
  zabbix-externalscripts:
  zabbix-enc:
  zabbix-mibs:
  zabbix-modules:
  zabbix-snmptraps:
  zabbix-ssh_keys:
  zabbix-ssl-certs:
  zabbix-ssl-keys:
  zabbix-ssl-ssl_ca:
  zabbix-mysql-data:
  zabbix-web-data:

networks:
   zabbix-network:
      ipam:
         config:
         - subnet: 172.19.0.0/16
           gateway: 172.19.0.1
